#!/usr/bin/env python

import os
import sys

#os.environ['DJANGO_SETTINGS_MODULE'] = 'comebh.settings'
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'app'))
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'app', 'comebh'))

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except:
    pass

os.environ['APPLICATION_ENVIRONMENT'] = 'production'

import app.comebh.wsgi
application = app.comebh.wsgi.application
